doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        enable_native_lazy_objects: true
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            SystemeioTestTask:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'SystemeioTestTask\Entity'
                alias: SystemeioTestTask
# turn it on if you'd like to use the bundle's User and the "user manageable" functionality for entities
#            SystemeioTestTask:
#                is_bundle: false
#                dir: '%kernel.project_dir%/vendor/g123udini/component-bundle/src/Entity'
#                prefix: 'DDH\ComponentBundle\Entity'
#                alias: DDH
#        dql:
#            string_functions:
#                GROUP_CONCAT: DDH\ComponentBundle\Doctrine\Mysql\GroupConcat

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
