CREATE USER dev WITH PASSWORD 'dev';
CREATE USER test WITH PASSWORD 'test';

CREATE DATABASE dev OWNER dev;
CREATE DATABASE test OWNER test;

GRANT ALL PRIVILEGES ON DATABASE dev TO dev;
GRANT ALL PRIVILEGES ON DATABASE test TO test;
