<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260905122810 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create product/coupon tables and seed example products and coupons.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE coupon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, type VARCHAR(255) NOT NULL, value INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64BF3F0277153098 ON coupon (code)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price_cents INT NOT NULL, PRIMARY KEY (id))');

        // Example catalogue from the test task spec (prices in cents).
        $this->addSql("INSERT INTO product (name, price_cents) VALUES ('Iphone', 10000)");
        $this->addSql("INSERT INTO product (name, price_cents) VALUES ('Наушники', 2000)");
        $this->addSql("INSERT INTO product (name, price_cents) VALUES ('Чехол', 1000)");

        // Coupon code convention: P<n> = n% off, D<n> = n EUR off (see requests.http).
        $this->addSql("INSERT INTO coupon (code, type, value) VALUES ('P10', 'percent', 10)");
        $this->addSql("INSERT INTO coupon (code, type, value) VALUES ('P100', 'percent', 100)");
        $this->addSql("INSERT INTO coupon (code, type, value) VALUES ('D15', 'fixed', 1500)");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE product');
    }
}
