CREATE DATABASE IF NOT EXISTS dev COLLATE utf8mb4_general_ci CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS test COLLATE utf8mb4_general_ci CHARACTER SET utf8mb4;

CREATE USER dev@'%' IDENTIFIED BY 'dev';
CREATE USER test@'%' IDENTIFIED BY 'test';

GRANT ALL PRIVILEGES ON dev.* TO 'dev'@'%';
GRANT ALL PRIVILEGES ON test.* TO 'test'@'%';
